export type Language = "ru" | "kg" | "en";

export const translations = {
  ru: {
    "nav.home": "Главная", "nav.about": "Об академии", "nav.training": "Подготовка", "nav.branches": "Филиалы", "nav.gallery": "Галерея", "nav.franchise": "Франчайзинг", "nav.register": "Записаться", "nav.menu": "Открыть меню",
    "hero.title": "Футбольная академия имени Асылбека Момунова", "hero.enrollment": "Набор детей от 6 до 16 лет.", "hero.description": "Мы готовим будущих игроков национальной сборной Кыргызстана и профессиональных клубов, а также воспитываем тренеров, менеджеров и лидеров, которые будут развивать футбол страны.", "hero.cta": "Записаться", "hero.branches": "Наши филиалы", "hero.follow": "Следите за нами →",
    "about.eyebrow": "01 / Об академии", "about.title": "Путь ребёнка — к большому футболу.", "about.description": "Наша цель — не просто научить ребёнка играть в футбол. Мы создаём среду, в которой дети могут пройти путь от первых тренировок до профессионального футбола и получить ценности, которые помогут им стать лидерами в спорте и жизни.", "about.partners": "Партнёры академии: FIFA, AFC, KFU и AFIM", "about.partnersText": "При поддержке FIFA, AFC и Кыргызского футбольного союза Академия футбола имени Асылбека Момунова реализует современные программы подготовки молодых футболистов и развивает детский футбол в Кыргызстане.",
    "about.value1.title": "Профессиональный путь", "about.value1.description": "Помогаем пройти путь от первых тренировок к серьёзным футбольным целям.", "about.value2.title": "Высокие достижения", "about.value2.description": "Закладываем фундамент для интенсивной подготовки и спортивного роста.", "about.value3.title": "Характер и лидерство", "about.value3.description": "Воспитываем дисциплину, ответственность и умение вести за собой.", "about.value4.title": "Футбол страны", "about.value4.description": "Развиваем будущих тренеров, менеджеров и специалистов индустрии.",
    "sponsors.label": "Партнёры AFIM",
    "programs.eyebrow": "02 / Группы", "programs.title": "Каждая группа — ступень к большому футболу.", "programs.description": "Тренировочный процесс выстроен по возрасту, уровню подготовки и спортивным амбициям ребёнка.", "programs.age1": "6–8 лет", "programs.age2": "9–12 лет", "programs.age3": "13–16 лет", "programs.card1.title": "Старт большого пути", "programs.card1.description": "Формируем любовь к игре, координацию и базовые навыки будущего футболиста.", "programs.card2.title": "Фундамент игрока", "programs.card2.description": "Развиваем технику, скорость решений и понимание современного футбола.", "programs.card3.title": "Подготовка к уровню выше", "programs.card3.description": "Укрепляем физическую готовность, дисциплину и соревновательное мышление.",
    "coaches.eyebrow": "03 / Тренеры", "coaches.title": "Наставники для пути в большой футбол.", "coaches.description": "Наши тренеры помогают ребёнку расти как игроку, лидеру и будущему представителю футбольной индустрии. Требовательность здесь всегда идёт рядом с вниманием и поддержкой.", "coaches.cta": "Узнать о тренировках",
    "branches.eyebrow": "04 / Филиалы", "branches.title": "Большой футбол начинается рядом с домом.", "branches.description": "Выберите удобный филиал и начните путь ребёнка к сильной футбольной школе.", "branches.label": "ФИЛИАЛ", "branches.map": "Показать на карте", "branches.mapTitle": "Карта филиалов", "branches.mapDescription": "Откройте карточку филиала, чтобы построить маршрут в привычном сервисе карт.",
    "gallery.eyebrow": "05 / Галерея", "gallery.title": "Каждая тренировка — часть большой игры.", "gallery.follow": "Следить за AFIM →", "gallery.card1.title": "Техника", "gallery.card1.description": "Развиваем навыки, необходимые для современного футбола.", "gallery.card2.title": "Команда", "gallery.card2.description": "Учим играть ради общей цели и быть частью коллектива.", "gallery.card3.title": "Характер", "gallery.card3.description": "Воспитываем дисциплину, ответственность и лидерские качества.", "gallery.card4.title": "Игра", "gallery.card4.description": "Готовим детей к настоящему соревновательному футболу.", "gallery.imageAlt": "Тренировка AFIM",
    "franchise.eyebrow": "06 / Франчайзинг", "franchise.title": "Хотите растить новое поколение футбольных лидеров вместе с AFIM?", "franchise.description": "Расскажем о стандартах академии и формате сотрудничества, который помогает развивать футбол в регионах Кыргызстана.", "franchise.cta": "Обсудить сотрудничество",
    "contact.eyebrow": "07 / Контакты", "contact.title": "Начните путь ребёнка в большой футбол.", "contact.description": "Оставьте заявку — команда AFIM поможет выбрать группу и сделать первый шаг к футбольным достижениям.", "contact.address": "г. Ош", "contact.instagram": "Наш Instagram",
    "footer.description": "Воспитываем новое поколение футболистов и лидеров футбола Кыргызстана.", "footer.training": "Подготовка",
  },
  kg: {
    "nav.home": "Башкы бет", "nav.about": "Академия жөнүндө", "nav.training": "Даярдык", "nav.branches": "Филиалдар", "nav.gallery": "Галерея", "nav.franchise": "Франчайзинг", "nav.register": "Катталуу", "nav.menu": "Менюну ачуу",
    "hero.title": "Асылбек Момунов атындагы футбол академиясы", "hero.enrollment": "6 жаштан 16 жашка чейинки балдарды кабыл алуу.", "hero.description": "Биз Кыргызстандын улуттук курама командасынын жана кесипкөй клубдардын келечектеги оюнчуларын даярдайбыз, ошондой эле өлкө футболун өнүктүрө турган машыктыруучуларды, менеджерлерди жана лидерлерди тарбиялайбыз.", "hero.cta": "Катталуу", "hero.branches": "Биздин филиалдар", "hero.follow": "Бизге катталыңыз →",
    "about.eyebrow": "01 / Академия жөнүндө", "about.title": "Баланын жолу — чоң футболго.", "about.description": "Биздин максат — баланы футбол ойноого гана үйрөтүү эмес. Биз балдар алгачкы машыгуудан кесипкөй футболго чейин өсүп, спортто жана жашоодо лидер болууга жардам бере турган баалуулуктарга ээ боло турган шарт түзөбүз.", "about.partners": "Академиянын өнөктөштөрү: FIFA, AFC, KFU жана AFIM", "about.partnersText": "FIFA, AFC жана Кыргыз футбол союзунун колдоосу менен Асылбек Момунов атындагы футбол академиясы жаш футболчуларды даярдоонун заманбап программаларын ишке ашырып, Кыргызстанда балдар футболун өнүктүрөт.",
    "about.value1.title": "Кесипкөй жол", "about.value1.description": "Алгачкы машыгуудан олуттуу футболдук максаттарга чейинки жолду басып өтүүгө жардам беребиз.", "about.value2.title": "Жогорку жетишкендиктер", "about.value2.description": "Интенсивдүү даярдык жана спорттук өсүү үчүн пайдубал түзөбүз.", "about.value3.title": "Мүнөз жана лидерлик", "about.value3.description": "Тартипти, жоопкерчиликти жана алдыга баштоо жөндөмүн тарбиялайбыз.", "about.value4.title": "Өлкө футбоду", "about.value4.description": "Келечектеги машыктыруучуларды, менеджерлерди жана тармак адистерин өстүрөбүз.",
    "sponsors.label": "AFIM өнөктөштөрү",
    "programs.eyebrow": "02 / Топтор", "programs.title": "Ар бир топ — чоң футболго карай баскыч.", "programs.description": "Машыгуу процесси баланын жашына, даярдык деңгээлине жана спорттук максатына жараша түзүлөт.", "programs.age1": "6–8 жаш", "programs.age2": "9–12 жаш", "programs.age3": "13–16 жаш", "programs.card1.title": "Чоң жолдун башталышы", "programs.card1.description": "Оюнга болгон сүйүүнү, координацияны жана келечектеги футболчунун негизги көндүмдөрүн калыптандырабыз.", "programs.card2.title": "Оюнчунун пайдубалы", "programs.card2.description": "Техниканы, чечим кабыл алуу ылдамдыгын жана заманбап футболду түшүнүүнү өнүктүрөбүз.", "programs.card3.title": "Кийинки деңгээлге даярдык", "programs.card3.description": "Физикалык даярдыкты, тартипти жана атаандаштык ой жүгүртүүнү бекемдейбиз.",
    "coaches.eyebrow": "03 / Машыктыруучулар", "coaches.title": "Чоң футбол жолундагы насаатчылар.", "coaches.description": "Машыктыруучуларыбыз балага оюнчу, лидер жана футбол тармагынын келечектеги өкүлү катары өсүүгө жардам берет. Талап коюу бул жерде ар дайым көңүл буруу жана колдоо менен коштолот.", "coaches.cta": "Машыгуулар тууралуу билүү",
    "branches.eyebrow": "04 / Филиалдар", "branches.title": "Чоң футбол үйдүн жанынан башталат.", "branches.description": "Ыңгайлуу филиалды тандап, балаңыздын күчтүү футбол мектебине жолун баштаңыз.", "branches.label": "ФИЛИАЛ", "branches.map": "Картадан көрсөтүү", "branches.mapTitle": "Филиалдардын картасы", "branches.mapDescription": "Кадимки карта кызматында жолду куруу үчүн филиалдын картасын ачыңыз.",
    "gallery.eyebrow": "05 / Галерея", "gallery.title": "Ар бир машыгуу — чоң оюндун бөлүгү.", "gallery.follow": "AFIM'ди ээрчүү →", "gallery.card1.title": "Техника", "gallery.card1.description": "Заманбап футболго керектүү көндүмдөрдү өнүктүрөбүз.", "gallery.card2.title": "Команда", "gallery.card2.description": "Жалпы максат үчүн ойноого жана жамааттын бөлүгү болууга үйрөтөбүз.", "gallery.card3.title": "Мүнөз", "gallery.card3.description": "Тартипти, жоопкерчиликти жана лидерлик сапаттарды тарбиялайбыз.", "gallery.card4.title": "Оюн", "gallery.card4.description": "Балдарды чыныгы атаандаштыкка даярдайбыз.", "gallery.imageAlt": "AFIM машыгуусу",
    "franchise.eyebrow": "06 / Франчайзинг", "franchise.title": "AFIM менен бирге футбол лидерлеринин жаңы муунун өстүргүңүз келеби?", "franchise.description": "Академиянын стандарттары жана Кыргызстан аймактарында футболду өнүктүрүүгө көмөктөшкөн кызматташтык форматы жөнүндө айтып беребиз.", "franchise.cta": "Кызматташтыкты талкуулоо",
    "contact.eyebrow": "07 / Байланыштар", "contact.title": "Чоң футболго жолду баштаңыз.", "contact.description": "Өтүнмө калтырыңыз — AFIM командасы топту тандоого жана футболдук жетишкендиктерге алгачкы кадам таштоого жардам берет.", "contact.address": "Ош ш.", "contact.instagram": "Биздин Instagram",
    "footer.description": "Кыргызстан футболунун жаңы муундагы оюнчуларын жана лидерлерин тарбиялайбыз.", "footer.training": "Даярдык",
  },
  en: {
    "nav.home": "Home", "nav.about": "About", "nav.training": "Training", "nav.branches": "Branches", "nav.gallery": "Gallery", "nav.franchise": "Franchise", "nav.register": "Apply", "nav.menu": "Open menu",
    "hero.title": "Asylbek Momunov Football Academy", "hero.enrollment": "Enrollment for children aged 6 to 16.", "hero.description": "We prepare future players for the Kyrgyzstan national team and professional clubs, while nurturing coaches, managers, and leaders who will develop football in the country.", "hero.cta": "Apply", "hero.branches": "Our branches", "hero.follow": "Follow us →",
    "about.eyebrow": "01 / About the academy", "about.title": "A child’s path to great football.", "about.description": "Our goal is not only to teach a child to play football. We create an environment where children can grow from their first sessions to professional football and gain values that help them become leaders in sport and life.", "about.partners": "Academy partners: FIFA, AFC, KFU and AFIM", "about.partnersText": "With the support of FIFA, AFC and the Kyrgyz Football Union, the Asylbek Momunov Football Academy delivers modern programmes for young footballers and develops youth football in Kyrgyzstan.",
    "about.value1.title": "Professional path", "about.value1.description": "We help children move from their first sessions to meaningful football goals.", "about.value2.title": "High achievement", "about.value2.description": "We build a foundation for intensive training and sporting growth.", "about.value3.title": "Character and leadership", "about.value3.description": "We nurture discipline, responsibility and the ability to lead.", "about.value4.title": "Football for the country", "about.value4.description": "We develop future coaches, managers and industry specialists.",
    "sponsors.label": "AFIM partners",
    "programs.eyebrow": "02 / Groups", "programs.title": "Every group is a step towards great football.", "programs.description": "The training process is designed around each child’s age, preparation level and sporting ambitions.", "programs.age1": "Ages 6–8", "programs.age2": "Ages 9–12", "programs.age3": "Ages 13–16", "programs.card1.title": "The start of a great journey", "programs.card1.description": "We build a love for the game, coordination and core football skills.", "programs.card2.title": "A player’s foundation", "programs.card2.description": "We develop technique, speed of decision-making and an understanding of modern football.", "programs.card3.title": "Preparation for the next level", "programs.card3.description": "We strengthen physical readiness, discipline and competitive thinking.",
    "coaches.eyebrow": "03 / Coaches", "coaches.title": "Mentors for the journey to great football.", "coaches.description": "Our coaches help every child grow as a player, a leader and a future representative of the football industry. High expectations always go hand in hand with care and support.", "coaches.cta": "Learn about training",
    "branches.eyebrow": "04 / Branches", "branches.title": "Great football starts close to home.", "branches.description": "Choose a convenient branch and begin your child’s journey to a strong football school.", "branches.label": "BRANCH", "branches.map": "Show on map", "branches.mapTitle": "Branch map", "branches.mapDescription": "Open a branch card to build a route in your preferred map service.",
    "gallery.eyebrow": "05 / Gallery", "gallery.title": "Every training session is part of the big game.", "gallery.follow": "Follow AFIM →", "gallery.card1.title": "Technique", "gallery.card1.description": "We develop the skills needed for modern football.", "gallery.card2.title": "Team", "gallery.card2.description": "We teach children to play for a shared goal and be part of a team.", "gallery.card3.title": "Character", "gallery.card3.description": "We nurture discipline, responsibility and leadership qualities.", "gallery.card4.title": "The game", "gallery.card4.description": "We prepare children for real competition.", "gallery.imageAlt": "AFIM training session",
    "franchise.eyebrow": "06 / Franchise", "franchise.title": "Would you like to raise a new generation of football leaders with AFIM?", "franchise.description": "We will share our academy standards and a cooperation model that helps develop football across Kyrgyzstan’s regions.", "franchise.cta": "Discuss cooperation",
    "contact.eyebrow": "07 / Contacts", "contact.title": "Start your child’s path to great football.", "contact.description": "Leave an application — the AFIM team will help choose a group and take the first step towards football achievements.", "contact.address": "Osh", "contact.instagram": "Our Instagram",
    "footer.description": "We nurture a new generation of footballers and football leaders in Kyrgyzstan.", "footer.training": "Training",
  },
} as const;

export type TranslationKey = keyof typeof translations.ru;

export function getTranslation(language: Language) {
  return translations[language];
}
